docs: add toufyx example configuration
feline-nvim/feline.nvim pull request #297
Opened 2022-08-31 05:45 UTC by Toufyx

2022-09-01 14:59 UTC, famiu requested changes
Remove the extra blank line

2022-09-02 08:38 UTC, Toufyx commented on README.md
> +
```suggestion
```

2022-09-02 08:39 UTC, Toufyx commented
> Remove the extra blank line

Done :)

2022-09-02 12:04 UTC, famiu approved these changes

2022-09-02 12:04 UTC, merged