feat: Added provider search_count
feline-nvim/feline.nvim pull request #322
Opened 2022-10-24 23:44 UTC by LucasTavaresA

Now that [cmd_height](https://github.com/neovim/neovim/pull/16251) can be set to zero, i think this is a nice addition to feline
idk how to categorize this tho

2022-10-25 08:45 UTC, famiu commented on doc/feline.txt
> +│feline-search_count           │Current search total/current word count    │
Do not modify Vim docs on your own, this will be autogenerated by a CI job. Modifying the USAGE.md file is enough

2022-10-25 09:10 UTC, famiu requested changes

2022-10-25 13:52 UTC, LucasTavaresA commented on lua/feline/providers/cursor.lua
> +    if vim.v.hlsearch == 0 then
when i check for nil the search counter never disappears even when neovim just opened or when you press `:noh`

2022-10-25 17:15 UTC, famiu commented on lua/feline/providers/cursor.lua
> +    if vim.v.hlsearch == 0 then
Fair enough, I guess it's fine to keep this check. But we should probably clarify in docs that it requires `'hlsearch'`

2022-10-25 18:17 UTC, LucasTavaresA commented on lua/feline/providers/cursor.lua
> +    if vim.v.hlsearch == 0 then
Just added this to `USAGE.md`

2022-10-26 06:12 UTC, famiu commented on USAGE.md
> +Needs [hlsearch](https://neovim.io/doc/user/options.html#'hlsearch') to be able to show the count.
```suggestion
This option requires `'hlsearch'` (see `:h 'hlsearch'` in Neovim) in order for it to work.
```

2022-10-26 07:32 UTC, famiu approved these changes
Thanks for your contribution :)

2022-10-26 07:33 UTC, merged